//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormSigno.SRSigno {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRSigno.HoroscoposSoap")]
    public interface HoroscoposSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento SignosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signos", ReplyAction="*")]
        FormSigno.SRSigno.SignosResponse Signos(FormSigno.SRSigno.SignosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Signos", ReplyAction="*")]
        System.Threading.Tasks.Task<FormSigno.SRSigno.SignosResponse> SignosAsync(FormSigno.SRSigno.SignosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Signos", Namespace="http://tempuri.org/", Order=0)]
        public FormSigno.SRSigno.SignosRequestBody Body;
        
        public SignosRequest() {
        }
        
        public SignosRequest(FormSigno.SRSigno.SignosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int dia;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int mes;
        
        public SignosRequestBody() {
        }
        
        public SignosRequestBody(int dia, int mes) {
            this.dia = dia;
            this.mes = mes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignosResponse", Namespace="http://tempuri.org/", Order=0)]
        public FormSigno.SRSigno.SignosResponseBody Body;
        
        public SignosResponse() {
        }
        
        public SignosResponse(FormSigno.SRSigno.SignosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SignosResult;
        
        public SignosResponseBody() {
        }
        
        public SignosResponseBody(string SignosResult) {
            this.SignosResult = SignosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HoroscoposSoapChannel : FormSigno.SRSigno.HoroscoposSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HoroscoposSoapClient : System.ServiceModel.ClientBase<FormSigno.SRSigno.HoroscoposSoap>, FormSigno.SRSigno.HoroscoposSoap {
        
        public HoroscoposSoapClient() {
        }
        
        public HoroscoposSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HoroscoposSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoroscoposSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HoroscoposSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormSigno.SRSigno.SignosResponse FormSigno.SRSigno.HoroscoposSoap.Signos(FormSigno.SRSigno.SignosRequest request) {
            return base.Channel.Signos(request);
        }
        
        public string Signos(int dia, int mes) {
            FormSigno.SRSigno.SignosRequest inValue = new FormSigno.SRSigno.SignosRequest();
            inValue.Body = new FormSigno.SRSigno.SignosRequestBody();
            inValue.Body.dia = dia;
            inValue.Body.mes = mes;
            FormSigno.SRSigno.SignosResponse retVal = ((FormSigno.SRSigno.HoroscoposSoap)(this)).Signos(inValue);
            return retVal.Body.SignosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormSigno.SRSigno.SignosResponse> FormSigno.SRSigno.HoroscoposSoap.SignosAsync(FormSigno.SRSigno.SignosRequest request) {
            return base.Channel.SignosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormSigno.SRSigno.SignosResponse> SignosAsync(int dia, int mes) {
            FormSigno.SRSigno.SignosRequest inValue = new FormSigno.SRSigno.SignosRequest();
            inValue.Body = new FormSigno.SRSigno.SignosRequestBody();
            inValue.Body.dia = dia;
            inValue.Body.mes = mes;
            return ((FormSigno.SRSigno.HoroscoposSoap)(this)).SignosAsync(inValue);
        }
    }
}
